# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.35.1"

default_platform :android

platform :android do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  lane :playstore do
    gradle(
      task: 'assemble',
      build_type: 'Release'
    )
  end

  desc "Submit a new Beta Build to Crashlytics Beta"


  lane :beta do
  increment_version_code
  commit_android_version_bump
  push_to_git_remote

  gradle(task: "assembleRelease")
  changelog_from_git_commits

  crashlytics(emails ['sadiga80@gmail.com','santhosh.adiga@accionlabs.com'])

  slack

  end

  lane :submit_unity_beta do
       crashlytics(
         emails: "santhosh.adiga@accionlabs.com",
         apk_path: "app/build/outputs/apk/app-debug.apk"
         api_token: " d2134a1a1eeb3d5d814cfaf373e2632dc5ed5761",
             build_secret: " 2ce65a5de94b6d84a80b1d8b8168358db6764e87da518295cc48d56298c80089"

       )
    end



  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded. 
# Learn more at https://github.com/fastlane/fastlane#metrics
